[package]
name = "routecore"
version = "0.2.1-dev"
authors = ["The NLnet Labs RPKI team <rpki-team@nlnetlabs.nl>"]
categories = ["network-programming"]
description = "A Library with Building Blocks for BGP Routing"
documentation = "https://docs.rs/routecore/"
edition = "2021"
rust-version = "1.63"
keywords = ["routing", "bgp"]
license = "BSD-3-Clause"

[dependencies]

# Optional dependencies which, if included, introduce additional functionality.
arbitrary = { version = "1", optional = true, features = ["derive"] }
bcder = { version = "0.7.0", optional = true }
serde = { version = "1.0.95", optional = true, features = ["derive"] }

[dev-dependencies]
serde_test      = "1.0"

[features]
default = []
