[package]
authors = ["The NLnet Labs RPKI team <rpki-team@nlnetlabs.nl>"]
categories = ["network-programming"]
description = "A Library with Building Blocks for BGP Routing"
documentation = "https://docs.rs/routecore/"
edition = "2018"
homepage = "https://nlnetlabs.nl/projects/routing/rotonda/"
keywords = ["routing", "bgp"]
license = "BSD-3-Clause"
name = "routecore"
version = "0.0.2-dev"

[dependencies]
num = "^0.3"
serde = {version = "1.0.95", optional = true, features = ["derive"]}

[dev-dependencies]
serde_json      = "1.0.40"
serde_test      = "1.0"

[features]
default = []
