[package]
name = "routecore"
version = "0.2.0"
authors = ["The NLnet Labs RPKI team <rpki-team@nlnetlabs.nl>"]
categories = ["network-programming"]
description = "A Library with Building Blocks for BGP Routing"
documentation = "https://docs.rs/routecore/"
edition = "2018"
keywords = ["routing", "bgp"]
license = "BSD-3-Clause"

[dependencies]

# Optional dependencies which, if included, introduce additional functionality.
bcder = { version = "0.7.0", optional = true }
serde = { version = "1.0.95", optional = true, features = ["derive"] }

[dev-dependencies]
serde_test      = "1.0"

[features]
default = []
