[package]
name = "routecore"
version = "0.3.0-dev"
authors = ["The NLnet Labs RPKI team <rpki-team@nlnetlabs.nl>"]
categories = ["network-programming"]
description = "A Library with Building Blocks for BGP Routing"
documentation = "https://docs.rs/routecore/"
edition = "2021"
rust-version = "1.56.1"
keywords = ["routing", "bgp"]
license = "BSD-3-Clause"

[dependencies]

# Optional dependencies which, if included, introduce additional functionality.
bcder = { version = "0.7.0", optional = true }
serde = { version = "1.0.95", optional = true, features = ["derive"] }


bytes = { version = "1.1.0", optional = true }
chrono = { version = "0.4", optional = true }
const-str = { version = "0.5.3", optional = true, features = ["case"] }
log = { version = "0.4.17", optional = true }

octseq = { git = "https://github.com/NLnetLabs/octseq", features = ["bytes"], branch="various-fixes", optional = true }
tokio = { version = "1", features = ["sync", "rt"], optional = true }

[dev-dependencies]
serde_test      = "1.0"

[features]
default = []
bgpfsm = ["bgp", "tokio"]
bgp = ["bytes", "log", "octseq", "const-str"]
bmp = ["bgp", "bytes", "chrono", "log", "octseq"]
std = []
