[package]
authors = ["The NLnet Labs RPKI team <rpki-team@nlnetlabs.nl>"]
categories = ["network-programming"]
description = "A Library with Building Blocks for BGP Routing"
documentation = "https://docs.rs/routecore/"
edition = "2018"
homepage = "https://nlnetlabs.nl/projects/routing/rotonda/"
keywords = ["routing", "bgp"]
license = "BSD-3-Clause"
name = "routecore"
version = "0.0.2-dev"

[dependencies]

# Optional dependencies which, if included, introduce additional functionality.
bcder = { version = "0.6", optional = true }
serde = { version = "1.0.95", optional = true, features = ["derive"] }

[dev-dependencies]
serde_test      = "1.0"

[features]
default = []
