name: ci
on: [push, pull_request]
jobs:
  checks:
    name: All checks
    needs: [test, clippy, audit, shear]
    runs-on: docker

  test:
    name: Test ${{ matrix.rust }} ${{ matrix.args }}
    runs-on: docker
    strategy:
      matrix:
        rust: [1.85, stable, beta]
        #args: ["--no-default-features", "", "--all-features"]
        args: ["", "--all-features"]
        target: [x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - name: cargo build --target=${{ matrix.target }} --verbose ${{ matrix.args }}
        run: cargo build --target=${{ matrix.target }} --verbose ${{ matrix.args }}
      - run: cargo test --target=${{ matrix.target }} --verbose ${{ matrix.args }}
      # Test using minimal dependency versions from Cargo.toml
      - name: Check and test with minimal-versions
        if: matrix.rust != 'beta'
        uses: https://github.com/dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          run: |
            cargo +nightly update -Z minimal-versions
            cargo build --verbose --all --all-features
            cargo test --verbose --all --all-features

  clippy:
    name: Clippy ${{ matrix.args }}
    runs-on: docker
    strategy:
      matrix:
        #args: ["--no-default-features", "", "--all-features"]
        args: ["", "--all-features"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --all ${{ matrix.args }} -- -W clippy::cargo # -D warnings

  cargo-binstall:
    name: Cargo binstall
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-binstall
        uses: https://github.com/cargo-bins/cargo-binstall@main
      - name: Install audit, shear
        run: cargo binstall --no-confirm cargo-audit cargo-shear
      - uses: actions/cache/save@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-binstall

  audit:
    name: Cargo audit
    runs-on: docker
    needs: [cargo-binstall]
    steps:
      - uses: actions/cache/restore@v5
        with:
          key: ${{ runner.os }}-cargo-binstall
        # RUSTSEC-2024-0436: paste - no longer maintained
      - run: cargo audit --ignore RUSTSEC-2024-0436

  shear:
    name: Cargo shear
    runs-on: docker
    needs: [cargo-binstall]
    steps:
      - uses: actions/cache/restore@v5
        with:
          key: ${{ runner.os }}-cargo-binstall
      - run: cargo shear
