name: ci
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [1.71, stable, beta]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}

    # Because of all the features, we run build and test twice -- once with
    # full features and once without any features at all -- to make it more
    # likely that everything works.

    # Clippy.
    #
    # For stable, error out on warnings.
    - if: matrix.rust == 'stable'
      run: |
        rustup component add clippy
        cargo clippy --all --all-features -- -D warnings

    # For beta, do not error out on warnings.
    - if: matrix.rust == 'beta'
      id: clippy_beta
      run: |
        rustup component add clippy
        # temporarily warn on clippy::cargo lints, to see if the next if is
        # triggered and working as expected
        {
          echo 'warnings=<<EOF'
          cargo clippy --all --all-features -q -- -W clippy::cargo
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - if: ${{ steps.clippy_beta.outputs.warnings }} != ''
      run: echo "::warning ${{ steps.clippy_beta.outputs.warnings }}"


    # Build
    - run: cargo build --verbose --all --all-features
    - run: cargo build --verbose --all

    # Test
    - run: cargo test --verbose --all --all-features
    - run: cargo test --verbose --all

    # Test using minimal dependency versions from Cargo.toml
    - if: matrix.rust != 'beta'
      run: |
        rustup toolchain install nightly
        cargo +nightly update -Z minimal-versions
        cargo build --verbose --all --all-features
        cargo test --verbose --all --all-features
      name: Check and test with minimal-versions
